Fixes Development environment check
Railcraft/Railcraft pull request #1099
Opened 2017-03-06 16:38 UTC by liach

Fixes #1098
Normal game runs in Searge names, so `World` class is always present, causing issues.
Instead, field names are in `field_123456_a` forms, so getting a field by name may check if the game is running in a development environment, which, in theory, has fields deobfuscated.
Edited on GitHub since I am away from home.
Will wait for travis status.

2017-03-06 22:44 UTC, CovertJaguar requested changes
You should have changed OBFUSCATED, not DEV_ENV.

Any build tagged with "alpha" or "beta" is a development build.

2017-03-07 15:52 UTC, liach commented
@CovertJaguar Do you still want this? Unfortunately, I do not have much time recently to work on this.

2017-03-08 22:03 UTC, liach commented
@CovertJaguar Fixed

2017-03-08 23:01 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/misc/Game.java
> +        DEVELOPMENT_ENVIRONMENT = !Railcraft.getVersion().matches(".*(alpha|beta).*") || !OBFUSCATED;
Huh....is it just me or this logic wrong? Not alpha or beta?

2017-03-08 23:15 UTC, CovertJaguar approved these changes
Looks good.

2017-03-08 23:16 UTC, merged