Minor Cosmetic Recipe Changes
Railcraft/Railcraft pull request #1119
Opened 2017-03-21 16:36 UTC by Generalcamo

Closes #1100 
Part of #1103 

Made packed ice applicable for Frostbound Brick recipe
Deprecated Bleached Clay, commented out for possible usage later (as pointed out by liach)
Smelt Bone Block for Bleached Bone Block (Similar to Abyssal Stone and Quarried Stone)

2017-03-21 18:54 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +                    'L', "gemLapis");
`dyeBlue`?

2017-03-21 18:55 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +//            CraftingPlugin.addShapelessRecipe(RailcraftItems.BLEACHED_CLAY.getStack(), new ItemStack(Items.CLAY_BALL), new ItemStack(Items.DYE, 1, 15), new ItemStack(Items.DYE, 1, 15), new ItemStac
You can remove these comments.

2017-03-21 19:06 UTC, liach requested changes

2017-03-21 19:06 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +//            CraftingPlugin.addShapelessRecipe(RailcraftItems.BLEACHED_CLAY.getStack(), new ItemStack(Items.CLAY_BALL), new ItemStack(Items.DYE, 1, 15), new ItemStack(Items.DYE, 1, 15), new ItemStac
Just remove these lines, recipe code is always the easiest code.

2017-03-21 20:19 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +                    'L', "gemLapis");
That's a possibility. But I want @CovertJaguar to put his opinion on that before I do it. He might have intentionally done that in the first place.

2017-03-21 23:29 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +                    'L', "gemLapis");
So I put this part in normal comment instead of the request for change.

2017-03-21 23:29 UTC, liach approved these changes

2017-03-22 00:50 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +                    'L', "gemLapis");
Yes, Lapis only.

2017-03-22 00:51 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +            CraftingPlugin.addFurnaceRecipe(new ItemStack(Blocks.BONE_BLOCK), new ItemStack(block, 1, 2), 0.3F);
Is this not a massive nerf to the recipe? It triples the cost. I know I'd never be able to build with them at this price.

2017-03-22 01:36 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +            CraftingPlugin.addFurnaceRecipe(new ItemStack(Blocks.BONE_BLOCK), new ItemStack(block, 1, 2), 0.3F);
To an extent. Clay is much harder to come by than Bone (as it is not renewable, and it requires aqua affinity and/or respiration for efficient mining of it). This recipe uses fully renewable resources.

If expense is a concern, doubling the amount gained from Smelting might be an option. There is no way to go back to a regular bone block, so there is no risk of duplication.

2017-03-22 01:47 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/brick/BrickTheme.java
> +            CraftingPlugin.addFurnaceRecipe(new ItemStack(Blocks.BONE_BLOCK), new ItemStack(block, 1, 2), 0.3F);
Bones only become cheap once you build some kind of mob farm, and even then, unless its an especially cheesy, tps breaking one, the output isn't that great.

Doubling the output would be fine.

2017-03-22 22:26 UTC, merged