Reorganized to make Railcraft more modular
Railcraft/Railcraft pull request #1177
Opened 2017-04-26 06:11 UTC by liach

Now every railcraft object has a module.
When the module is disabled, the object is also disabled. Moved recipe registering to init stage to avoid conflicts with mods like immersive engineering (reported before). Also avoided unorganized loading of objects because of unorganized recipes. Removed silly code in `ItemLocoElectric.java`. Added more fancy info of item register failure. Finally, Fixes #1167, tested with signal module disabled. Before the game crashes when the villager unlocks tier 3 trade, and now trades with signal items simply disappear. Same stack trace in the end, although neat mod was not involved.

2017-04-26 22:40 UTC, CovertJaguar commented
You realize items are intentionally intended to have lazy initialization right? They are only enabled if something uses them.

How is this an improvement on that?

2017-04-26 22:40 UTC, CovertJaguar requested changes
Make a case for why this should be accepted.

2017-04-26 22:54 UTC, liach commented
Main ideas:
1. Keeping a reference to the modules allows to find out specific issues when certain modules are disabled better.
2. Loading items and blocks during recipe definition is a bad behavior. They will be loaded in random order. Worst of all is that a recipe may load unwanted blocks/items from a disabled module.
3. Moving recipes from preinit to init is a necessity. See #662.

2017-04-26 23:02 UTC, CovertJaguar commented
1. Fair point

2. Items don't have modules... as I said, they are loaded as needed. This was by design.

3. I don't see how that issue is relevant as it refers to a specific recipe that was scanning the fluid registry for items.

2017-04-26 23:07 UTC, liach commented
Well, in the module classes, items are included by modules. 

> Items don't have modules... as I said, they are loaded as needed. This was by design. It helps to keep you from breaking your crafting tree.

This is what caused #1167: You expect items not to be modular but often times, when you find them in need, it is too late to load.

The last point is about most recipes, not only fluids. That is general design, I will ask @sfPlayer1.

2017-04-26 23:25 UTC, CovertJaguar requested changes

2017-04-26 23:25 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/modules/ModuleCore.java
> +                        RailcraftItems.TIE
Would track module be better?

2017-04-26 23:25 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java
> +                if (kit != TrackRegistry.getMissingTrackKit() && kit.isEnabled()) {
Probably check visible instead of missing.

2017-04-26 23:27 UTC, CovertJaguar commented
Ok, I did a thorough review and its not as crazy as it first looked. I'll probably break everything though, so I'll have to sit on it until I'm done with hotfixes for 10.1.0.

2017-04-27 00:47 UTC, liach commented
The trade on track kit is currently useless, we probably need some method to poll a random one like how librarians trade ench books.

2017-04-27 01:41 UTC, Generalcamo commented
Librarians use the Enchantment code to get a random enchant of x levels, which includes treasure enchants. That would be very difficult to implement.

2017-04-27 01:49 UTC, liach commented
@Generalcamo That support is within the registry of enchantment. If we need to do the same, we might seek to tweak track registry to make this more convenient (not necessary though)

2017-04-30 00:00 UTC, liach commented on src/main/java/mods/railcraft/common/modules/ModuleCore.java
> +                        RailcraftItems.TIE
Nope, this is in core in 1.7.

2017-04-30 00:01 UTC, liach commented on src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java
> +                if (kit != TrackRegistry.getMissingTrackKit() && kit.isEnabled()) {
#1181

2017-05-14 23:04 UTC, liach commented
@CovertJaguar Can you review?

2017-05-14 23:58 UTC, CovertJaguar commented
Oh right, I forgot about this.

2017-05-15 00:00 UTC, CovertJaguar approved these changes

2017-05-15 00:00 UTC, merged