Fix supplying null entries into the creative list
Railcraft/Railcraft pull request #1178
Opened 2017-04-26 06:50 UTC by liach

Fixed #1171 after the second commit. Before the game instantly crashes when you click that search tab. Now there is no effect, although loot table warns for missing items when the signal module is disabled (does not crash game)

2017-04-26 22:48 UTC, CovertJaguar requested changes
Removes the changes to Predicates, and it looks good.

2017-04-26 22:48 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/misc/Predicates.java
> +    private static final Predicate ALWAYS_TRUE = t -> true;
You are breaking the generics, keep your PRs focused. Ignoring the warnings is stupid.

2017-04-26 23:00 UTC, liach commented on src/main/java/mods/railcraft/common/util/misc/Predicates.java
> +    private static final Predicate ALWAYS_TRUE = t -> true;
It does not break. You should use `rawtypes`, just like `java.util.Collections.emptyList()` returns a generic list casted from a rawtype list. [Link to the source] (http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Collections.java#l4458)

2017-04-26 23:05 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/misc/Predicates.java
> +    private static final Predicate ALWAYS_TRUE = t -> true;
Why did you even make the change?

2017-04-26 23:42 UTC, liach commented on src/main/java/mods/railcraft/common/util/misc/Predicates.java
> +    private static final Predicate ALWAYS_TRUE = t -> true;
To prevent creating extra objects.

2017-04-27 01:35 UTC, CovertJaguar approved these changes

2017-04-27 01:35 UTC, merged