Fix #1153
Railcraft/Railcraft pull request #1181
Opened 2017-04-28 19:14 UTC by liach

Now villagers sell locomotives. I will adjust track kit trades, so this is work in progress.

2017-04-29 23:44 UTC, liach commented
@CovertJaguar Done.

2017-04-30 21:23 UTC, liach commented
Status?

2017-04-30 21:25 UTC, CovertJaguar requested changes

2017-04-30 21:25 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java
> +            ItemStack stack = trackKits.get(random.nextInt(trackKits.size())).getTrackKitItem(2);
This will crash if trackKits.size() == 0, which might be possible if everything is disabled.

2017-04-30 21:27 UTC, liach commented on src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java
> +            ItemStack stack = trackKits.get(random.nextInt(trackKits.size())).getTrackKitItem(2);
I believe in my coding ability on the web editor.

2017-04-30 21:30 UTC, CovertJaguar approved these changes

2017-04-30 21:31 UTC, liach commented
I'll squash and merge.

2017-04-30 21:31 UTC, merged