Refactors for track registry
Railcraft/Railcraft pull request #1208
Opened 2017-05-16 20:21 UTC by liach

Cleanup after api pull.
Seems it cannot grab the correct submodule, so it fails to build.
See https://github.com/CovertJaguar/Railcraft-API/pull/18

2017-05-16 23:30 UTC, liach commented
As long as you merge the api one first and rebuild, this will pass.

2017-05-17 00:03 UTC, CovertJaguar requested changes

2017-05-17 00:03 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/misc/Game.java
> +        OBFUSCATED = obfuscated;
Why are we changing this shit again? I just got done testing it in all possible environments. -.-

2017-05-17 00:05 UTC, liach commented on src/main/java/mods/railcraft/common/util/misc/Game.java
> +        OBFUSCATED = obfuscated;
Cuz this is done after merging. You should consider this as a merge conflict, and I will fix it too,

2017-05-18 01:48 UTC, CovertJaguar approved these changes

2017-05-18 01:53 UTC, liach commented
Let me fix submodules.

2017-05-18 01:59 UTC, liach commented
Guess I will merge this one first

2017-05-18 02:02 UTC, merged