Outfitted track speed should consider track type
Railcraft/Railcraft pull request #1210
Opened 2017-05-17 02:05 UTC by liach

Fixes #1202, high-speed booster track bug.
https://github.com/CovertJaguar/Railcraft-API/pull/19
Gave high-speed booster tracks a head start like other types.
Unified boost amount of transition and booster tracks.

2017-05-17 08:12 UTC, CovertJaguar requested changes

2017-05-17 08:12 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitSpeedTransition.java
> +    private static final double BOOST_AMOUNT = 0.06;
This directly impacts the number of transition tracks required. Don't change it.

2017-05-17 08:12 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/TrackKits.java
> +        });
Not needed.

2017-05-17 08:12 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitBooster.java
> +                }
If you are going to add this, extract the duplicated code in both pass functions to a new method.

2017-05-17 08:12 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitSpeedTransition.java
> +                }
This could probably share some code with the Booster if you are going to add it.

2017-05-17 08:12 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/BlockTrackOutfitted.java
> +            return ((TileTrackOutfitted) tile).getTrackKitInstance().getRailMaxSpeed(world, cart, pos, ((TileTrackOutfitted) tile).getTrackType());
TrackType parameter not needed.

2017-05-17 13:49 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitSpeedTransition.java
> +    private static final double BOOST_AMOUNT = 0.06;
I intended this to be consistejnt with high speed booster.

2017-05-17 16:41 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitSpeedTransition.java
> +    private static final double BOOST_AMOUNT = 0.06;
Yes, its not supposed to be.

2017-05-18 01:47 UTC, CovertJaguar approved these changes

2017-05-18 02:21 UTC, liach commented
So disturbing! I think it will be fine soon.

2017-05-18 02:26 UTC, merged