Fixed #1004, do not dump if there is block below
Railcraft/Railcraft pull request #1211
Opened 2017-05-17 02:46 UTC by liach

2017-05-17 10:06 UTC, CovertJaguar requested changes

2017-05-17 10:06 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitDumping.java
> +        if (!isPowered() && !theWorldAsserted().getBlockState(getPos().down()).getBlock().isVisuallyOpaque()) {
I'd suggest looking at the block below this as well, since it drops the entity two blocks down.

2017-05-17 13:51 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitDumping.java
> +        if (!isPowered() && !theWorldAsserted().getBlockState(getPos().down()).getBlock().isVisuallyOpaque()) {
That block does not hurt to players or villagers, etc. They cannot suffocate when their fepet is in block

2017-05-17 13:55 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitDumping.java
> +        if (!isPowered() && !theWorldAsserted().getBlockState(getPos().down()).getBlock().isVisuallyOpaque()) {
It still gets them stuck though, which is unintended behavior.

2017-05-17 13:57 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/tracks/outfitted/kits/TrackKitDumping.java
> +        if (!isPowered() && !theWorldAsserted().getBlockState(getPos().down()).getBlock().isVisuallyOpaque()) {
I don't think they will stuck. Anyways I will adjust it

2017-05-18 01:40 UTC, CovertJaguar approved these changes

2017-05-18 01:40 UTC, merged