Add Zinc and Brass
Railcraft/Railcraft pull request #1214
Opened 2017-05-17 13:50 UTC by Generalcamo

Adds Zinc and Brass to the game. They are currently of limited utility, but more uses will pop up as batteries are implemented, 10.3 is worked on, and we think of them.

Replaces Gold-Plated Gears, possibly breaking to other mods that use them (probably none).

2017-05-17 14:00 UTC, liach commented
See #1209

2017-05-17 14:02 UTC, liach approved these changes
Looks fine in the first glance but don't merge it.

2017-05-17 14:08 UTC, Generalcamo commented
![2017-05-17_01 27 15](https://cloud.githubusercontent.com/assets/1779662/26158052/b9b1b2b2-3ae8-11e7-8cb1-99be463dd551.png)
Brass and Zinc respectively

2017-05-17 16:39 UTC, CovertJaguar requested changes

2017-05-17 16:39 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/worldgen/GeneratorMineZinc.java
> +    private static final int Y_LEVEL = 40;
I suggest moving this to 30 so it generates on the same level as Lead, they are commonly found together.

2017-05-17 16:50 UTC, CovertJaguar approved these changes

2017-05-17 16:51 UTC, merged

2017-06-07 04:05 UTC, liach commented
@Generalcamo You forgot to add localization