Added boost enchantment
Railcraft/Railcraft pull request #1219
Opened 2017-05-21 22:49 UTC by liach

This enchantment is significant for its ability to boost a whole train over the common crowbars. Also formatted the configs a bit.

2017-05-21 22:51 UTC, liach commented
Lol I forgot localization entry.

2017-05-22 00:05 UTC, Generalcamo requested changes

2017-05-22 00:05 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        super("boost", rarity, EntityEquipmentSlot.MAINHAND);
You can boost with the off hand too, may want to change this.

2017-05-22 00:05 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
This is too high. This is an enchantment which has niche usage, and you are putting it on the level of Fire Aspect. 

I would recommend a base of 4 or so.

2017-05-22 00:13 UTC, liach commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        super("boost", rarity, EntityEquipmentSlot.MAINHAND);
Read more code! This has no effect as boosting is totally done in crowbar event handler.

2017-05-22 00:14 UTC, liach commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
You only know how powerful it is after testing it with a train, especially a long one.

2017-05-22 00:19 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        super("boost", rarity, EntityEquipmentSlot.MAINHAND);
Ahh my apologies then.

2017-05-22 00:20 UTC, liach commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        super("boost", rarity, EntityEquipmentSlot.MAINHAND);
Thanks.

2017-05-22 00:20 UTC, liach commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
I will post some test pictures.

2017-05-22 00:21 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
It still seem rather expensive honestly, for usage in derails and misc.

2017-05-22 00:27 UTC, liach commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
http://minecraft.gamepedia.com/Enchanting/Levels
The levels are composite, as the page referenced says in the red box, "These are not the levels you need to pay to be able to receive specific enchantments, you must also take into account the modification of levels that occur in step one."

2017-05-22 00:43 UTC, Generalcamo approved these changes

2017-05-22 00:44 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/enchantment/EnchantmentBoost.java
> +        return 9 + level * 8;
You make a fair point then. I guess we'll just test it in-game later.

2017-05-22 00:47 UTC, liach commented
Not really time to merge... CovertJaguar should test himself to make sure.

2017-05-22 01:25 UTC, liach commented
Uhh wait a bit, I still need to add localization entry.

2017-05-22 09:48 UTC, CovertJaguar requested changes

2017-05-22 09:48 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        trackingAuraEnabled = get(CAT_AURAS + ".goggles", "trackingAura", true, "Change to '{t}=false' to disable the Tracking Aura");
Why did you change this line at all?

2017-05-22 09:48 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        cat.keySet().removeIf(key -> key.startsWith("recipe"));
This is probably legacy code that could be removed entirely. Especially if it was added in 1.7 or earlier.

2017-05-22 09:48 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
Were we going to change this?

2017-05-22 13:51 UTC, liach commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
The nethod that this info uses takes an integer instead of a byte

2017-05-22 14:08 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
No, I meant the value.

2017-05-22 15:04 UTC, liach commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        cat.keySet().removeIf(key -> key.startsWith("recipe"));
You sure to remove that? I just saw this ugly code so that I changed it.

2017-05-22 15:07 UTC, liach commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
For reference, you should know that I had some issue with neptunepink on the server several hours ago. My crowbar lost more than 1/3 durability just to trying to get the derailed carts back on to the track. I think it should go down.

2017-05-22 15:08 UTC, liach commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        trackingAuraEnabled = get(CAT_AURAS + ".goggles", "trackingAura", true, "Change to '{t}=false' to disable the Tracking Aura");
I think this config entry is useful but I don't know what category does it belong to. It controls whether the aura is enabled and is used in code.

2017-05-22 15:27 UTC, Generalcamo commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
Well, then turn it down. 2 or even 1 would work.

2017-05-22 17:24 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +    private static final int BOOST_DAMAGE = 3;
I had a similar issue just trying push a cart up a muddy hill. 1 is fine.

2017-05-22 17:25 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        cat.keySet().removeIf(key -> key.startsWith("recipe"));
Check when it was added, its removing old entries. This is probably ancient code.

2017-05-22 17:26 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        trackingAuraEnabled = get(CAT_AURAS + ".goggles", "trackingAura", true, "Change to '{t}=false' to disable the Tracking Aura");
The aura that doesn't exist? That one?

2017-05-22 17:50 UTC, liach commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        trackingAuraEnabled = get(CAT_AURAS + ".goggles", "trackingAura", true, "Change to '{t}=false' to disable the Tracking Aura");
Eh, will work on it when I'm home.

2017-05-26 02:08 UTC, liach commented
I should rename this enchantment to whack

2017-05-26 03:03 UTC, liach commented
@CovertJaguar Can you review again?

2017-05-26 23:16 UTC, CovertJaguar commented
Config needs a lot of fixing, but I can do that.

2017-05-26 23:16 UTC, merged