respect gamerule for destruction
Railcraft/Railcraft pull request #1229
Opened 2017-05-27 18:08 UTC by liach

2017-05-27 18:35 UTC, liach commented
Also respected events and outfitted tracks

2017-05-28 00:46 UTC, liach commented
Should I include #1223 too?

2017-05-29 08:23 UTC, CovertJaguar commented
I was planning to rewrite it using the Timberjack block scanning algorithm.

2017-05-29 08:24 UTC, CovertJaguar requested changes

2017-05-29 08:24 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +        }
We should make this into a function in WorldPlugin.

2017-05-29 14:46 UTC, liach commented on src/main/java/mods/railcraft/common/items/ItemCrowbar.java
> +        }
Sounds good...

2017-05-29 14:46 UTC, liach commented
ref #872

2017-06-03 03:47 UTC, liach commented
@CovertJaguar Changed.

2017-06-03 15:45 UTC, CovertJaguar approved these changes

2017-06-03 15:48 UTC, merged