Adjusted link message to be above hotbar
Railcraft/Railcraft pull request #1253
Opened 2017-06-11 21:21 UTC by liach

Closes #1251 
![2017-06-11_14 17 03](https://user-images.githubusercontent.com/7806504/27014610-40f17f24-4eb1-11e7-8f58-25a70fa40dea.png)
![2017-06-11_14 17 06](https://user-images.githubusercontent.com/7806504/27014609-40f0e974-4eb1-11e7-8f88-8cce21f1b138.png)
![2017-06-11_14 17 17](https://user-images.githubusercontent.com/7806504/27014612-40f3736a-4eb1-11e7-9686-b4bc8022c01b.png)
![2017-06-11_14 17 30](https://user-images.githubusercontent.com/7806504/27014613-40f43a34-4eb1-11e7-9b93-32b63fa79948.png)
![2017-06-11_14 17 51](https://user-images.githubusercontent.com/7806504/27014611-40f1ddb6-4eb1-11e7-98f2-60d5aca8940b.png)

2017-06-11 22:45 UTC, liach commented
Should I change outfitted track placement message to be like these too?

2017-06-11 23:24 UTC, Generalcamo commented
This adds basically consistency with the changes in 1.11. I approve.

2017-06-12 08:09 UTC, liach commented
So I think we can put the message for track placement here too, but not those for commands.

2017-06-13 05:25 UTC, CovertJaguar requested changes

2017-06-13 05:25 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/ChatPlugin.java
> +            }
Copy paste code block? Split it out into a function please.

2017-06-13 17:08 UTC, CovertJaguar approved these changes

2017-06-13 17:09 UTC, merged