Various worldspike fixes
Railcraft/Railcraft pull request #1261
Opened 2017-06-20 05:58 UTC by liach

Fixes #1258
Fixes #847 - Always clean up when failing to pair. Now missing ones will
be said to be "invalid"
Also fixed localized name of worldspike points.

2017-06-20 05:59 UTC, liach commented
![2017-06-19_22 50 45](https://user-images.githubusercontent.com/7806504/27318777-037ea980-5543-11e7-9ae4-90e811976cdb.png)

2017-06-20 07:45 UTC, CovertJaguar requested changes
There is Style settings file in extras. Use it.

2017-06-20 07:59 UTC, CovertJaguar requested changes

2017-06-20 07:59 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
What is the point of this?

This is basically the same as getLocalizedName().

2017-06-20 13:33 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
In the localization file, the name of spike point has a .name following, so there is an issue in the message when pairing.

2017-06-20 17:02 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
Its the message that need fixing, not this.

2017-06-20 18:01 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
This is wrong because it is not from tiles. Will change in localization files then.

2017-06-20 18:01 UTC, liach commented
Everything else is fine right? Will fix tonight.

2017-06-21 02:19 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
What? no that's not right either.

2017-06-21 02:20 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
We are talking about the pairing messages right?

2017-06-21 02:21 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java
> +        return super.getUnlocalizedName() + ".name";
The localization files are supposed to have the ".name" suffix. getUnlocalizedName() returns the tag without the ".name" suffix. getLocalizedName() returns it with it.

Overriding getUnlocalizedName() is definitely the wrong solution for whatever you are trying to do.

2017-06-22 07:21 UTC, CovertJaguar approved these changes

2017-06-22 07:28 UTC, CovertJaguar requested changes

2017-06-22 07:28 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java
> +                        state.getBlock().getUnlocalizedName());
Are these wrong too?

2017-06-22 07:28 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java
> +        if (needsFuel()) {
Don't commit these style changes.

2017-06-22 14:22 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java
> +                        state.getBlock().getUnlocalizedName());
Just searched for usages in the block class, sorry.

2017-06-22 14:23 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java
> +        if (needsFuel()) {
For this I probably need to remake the whole thing.

2017-07-06 06:55 UTC, liach commented
@CovertJaguar Please review again.

2017-07-06 20:08 UTC, CovertJaguar approved these changes

2017-07-06 20:15 UTC, merged