Fluid and Tank cart fixes
Railcraft/Railcraft pull request #1285
Opened 2017-07-16 20:52 UTC by liach

Fixes #1194
Fixes #1248
Fixes #1270
Now both 3 slot and 2 slot systems work
Tested on my side

2017-07-16 20:54 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +    public static boolean isFailed(@Nullable ItemStack stack) {
This one fixes `isEmpty()`'s weakness that it cannot discern null stacks from used one-time container of stack size zero.

2017-07-16 20:54 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +    public static boolean isSuccessfullyConsumed(@Nullable ItemStack stack) {
This is for one-time containers, although it is not really used.

2017-07-16 20:55 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +        return ProcessState.DRAINING;
This has bugged me a lot, but I managed to fix this :smile: and one-time containers work then

2017-07-16 20:55 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +    public static boolean processContainers(StandardTank tank, IInventory inv, int inputSlot, int outputSlot) {
I've tested extensively with ic2 fluid cells and forestry one-time capsules. Working as intended.

2017-07-16 20:56 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> +    private Consumer<StandardTank> updateCallback;
This callback allows tank cart to get updated, and it works well.

2017-07-16 21:11 UTC, CovertJaguar requested changes

2017-07-16 21:11 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> -        if (!matchesFilter(resource))
Why remove this check? Its there to prevent bugs.

2017-07-16 21:11 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> +        if (!matchesFilter(resource))
This is unnecessary, its called via canFillFluidType() in super.fill().

2017-07-16 21:11 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> +    private Consumer<StandardTank> updateCallback;
👍

2017-07-16 21:11 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +        return ProcessState.DRAINING;
Copypasta bug ftw!

2017-07-16 21:11 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +    public static boolean processContainers(StandardTank tank, IInventory inv, int inputSlot, int outputSlot) {
And it will explode completely the instant you feed it a multi-bucket fluid container.

2017-07-16 21:12 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> -        if (!matchesFilter(resource))
This check is not for `fillInternal` according to the superclass' javadoc. It is for `fill` only, and you put it in the wrong spot.

2017-07-16 21:51 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/FluidTools.java
> +    public static boolean processContainers(StandardTank tank, IInventory inv, int inputSlot, int outputSlot) {
@CovertJaguar For that claim, we need to find one of those containers and test. Extrautil doesn't have one, we need to find others!

2017-07-16 22:13 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> -        if (!matchesFilter(resource))
No I didn't. I put it where it needed to be to prevent any possibility of filling with the wrong fluid.

2017-07-17 02:15 UTC, liach commented
@CovertJaguar Can you work on these pulls? I will not be able to devote a lot on these pulls in the following days.

2017-07-18 02:21 UTC, CovertJaguar approved these changes

2017-07-18 03:01 UTC, liach commented
@CovertJaguar I will left you decide which model you will take. I suggest you to take the 3 slot model. If you want to make the change, I suggest you changing the texture and adding the slot on your own, because I am not very good at that (Time is an issue too)

2017-07-18 03:02 UTC, merged