Add trade station cart
Railcraft/Railcraft pull request #1560
Opened 2018-12-07 22:47 UTC by liach

More leftovers:
Trade stations can dupe items as a result of the recent inv refactor. Needs fix.
Trade stations guis have weird color if f3+b bounding box render is on
The AI is weird, dunno if it really works.
The initial bytes for the trade station cart cannot really be improved given the data parameters are initialized before the fields in classes are. Decoding from each default logic is expensive and no less ugly.

**The Issue**
See #1093 comment for trade station cart.
 
**The Proposal**
 - Added carts module for disabling carts more easily
 - Changed how minecarts open guis (simpler now)
 - Moved trade station logic to a shared logic class for easy cleanups except entity/te specific parts
 - 
 
**Possible Side Effects**
 - Affects cart management in the future in config (new module)
 - Affects trade station behavior
 
**Alternatives**
No alternative is present except leaving this feature. The trade station cart reduce the need of moving villagers, which move on their own and might disrupt the minecarts' movements.

2018-12-09 09:16 UTC, liach commented
the compile error is caused by the missing dependencies for the test source set.

2018-12-11 03:55 UTC, CovertJaguar requested changes
Looks good generally, though the datawatcher stuff is definitely iffy.

2018-12-11 03:55 UTC, CovertJaguar commented on src/main/java/mods/railcraft/client/gui/FactoryGui.java
> +                    return new GuiTradeStation(inv, obj instanceof TileTradeStation ? ((TileTradeStation) obj).getLogic() : ((EntityCartTradeStation) obj).getLogic(), (IWorldNameable) obj);
Use an interface?

2018-12-11 03:55 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/gui/containers/FactoryContainer.java
> +                    return new ContainerTradeStation(inv, obj instanceof TileTradeStation ? ((TileTradeStation) obj).getLogic() : ((EntityCartTradeStation) obj).getLogic());
Again...interface

2018-12-11 03:55 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/modules/ModuleExtras.java
> +@RailcraftModule(value = "railcraft:extras", softDependencyClasses = {ModuleCarts.class, ModuleTracks.class}, description = "silly stuff, launch track, tnt carts, work cart")
Description needs an update.

2018-12-11 03:55 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/entity/ai/EntityAIMoveToEntity.java
> +public class EntityAIMoveToEntity extends EntityAIBase {
Rename to EntityAISearchForEntity, and the block version to EntityAISearchForBlock.

2018-12-12 07:44 UTC, liach commented
wtf github removed that merge button here. stupid enough

2018-12-13 03:41 UTC, CovertJaguar approved these changes

2018-12-13 03:44 UTC, CovertJaguar commented
FYI, your merge failed.

2018-12-13 05:17 UTC, liach commented
yeah, been lazy to fix it.

2018-12-17 23:30 UTC, merged