Add vm args (so players can change memory) and enable assertions for dev
Railcraft/Railcraft pull request #1569
Opened 2018-12-17 10:49 UTC by liach

Signed-off-by: liach <liach@users.noreply.github.com>

**The Issue**
 - Assertions are not enabled by default.
 - Dev-runners complain that they cannot change the RAM
 
**The Proposal**
 - Add run args in gradle to fix this issue
 
**Possible Side Effects**
 - The args are from https://redd.it/5jhuk9, should be valid
 
**Alternatives**
 - No change.

2018-12-17 16:28 UTC, Chocohead commented on build.gradle
> +def combinedVmArgs = [['-ea'], optimizedVmArgs].flatten()
You might want to add `-da:io.netty...` too if you're enabling assertions. Netty is a little careless with its assertions (or Minecraft/Forge isn't using it quite right) so mods using `IGuiHandler` can end up with assertion errors from within Netty.

2018-12-17 19:53 UTC, CovertJaguar commented on build.gradle
> +def combinedVmArgs = [['-ea'], optimizedVmArgs].flatten()
You _do not_ want enable assertions for anything but our code. Everything breaks.

2018-12-17 19:56 UTC, CovertJaguar requested changes

2018-12-17 19:56 UTC, CovertJaguar commented on build.gradle
> +def combinedVmArgs = [['-ea'], optimizedVmArgs].flatten()
This is my recommendation, but I'm not sure about the syntax here.
```
def combinedVmArgs = [['-ea:mods.railcraft...', '-ea:net.minecraft...', '-ea:net.minecraftforge...'], optimizedVmArgs].flatten()
```

2018-12-17 23:32 UTC, CovertJaguar approved these changes

2018-12-17 23:33 UTC, merged

2018-12-18 01:07 UTC, Chocohead commented on build.gradle
> +def combinedVmArgs = [['-ea'], optimizedVmArgs].flatten()
Neither Minecraft nor Forge use assertions so you're not gaining anything by adding them to the list, but neither are you losing I suppose