Update bug_report.md
Railcraft/Railcraft pull request #1600
Opened 2018-12-27 21:20 UTC by liach

So that people will know that they need to include the stack trace! It's weird that cj forgot this component.

2018-12-27 21:27 UTC, CovertJaguar requested changes

2018-12-27 21:27 UTC, CovertJaguar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!--Post your logs to https://gist.github.com/ or https://pastebin.com/ and link it below. Do not remove any part of the log!-->
I'd rather not promote pastebin. Too often by the time I get around to looking at it, it has been deleted.

2018-12-27 21:30 UTC, liach commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!--Post your logs to https://gist.github.com/ or https://pastebin.com/ and link it below. Do not remove any part of the log!-->
Hmm, so ubuntu paste? gist is blocked in china

2018-12-28 02:13 UTC, CovertJaguar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!--Post your logs to https://gist.github.com/ or https://pastebin.com/ and link it below. Do not remove any part of the log!-->
I guess pastebin no longer deletes pastes like it has in the past according to its FAQ.

2018-12-28 02:14 UTC, CovertJaguar approved these changes

2018-12-28 02:15 UTC, merged