Fixes #1583, fixes #1599, fixes #1653, fixes #1613, fixes #1567
Railcraft/Railcraft pull request #1655
Opened 2019-01-14 07:00 UTC by liach

**The Issue**
 - #1583 
 - #1599 
 - #1567 
 - #1563 
 - #1653 
 
**The Proposal**
 - #1583: optional map to bypass npe
 - #1567: serialize capacity in standard tank
 - #1599: added config option
 - #1653: return base state instead of getting default state from block
 - #1613: first part is #1583, second part is #1567 
 
**Possible Side Effects**
 - Will affect if cj is already refactoring these multiblocks
 - Boiler still has some issues and needs deeper digging.
 
**Alternatives**
For the config option, I allow people to set a large value so that people won't bitch if they include rc in zimbabwe watt packs.

2019-01-14 07:26 UTC, CovertJaguar requested changes
I think the real problem is that the capacity calc should be in onPatternChanged instead of onPatternLocked. That _should_ fix it without requiring changes to TankManager and StandardTank.

2019-01-14 07:26 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/multi/TileBoilerFirebox.java
> +        tankManager.writePacketData(data);
This is only required in things that render the FluidStack in a TESR.

2019-01-14 07:26 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/core/RailcraftConfig.java
> +        tankPerBlockCapacity = get(CAT_TWEAKS_BLOCKS + ".irontank", "capacity.per.block", 1, 16 * FluidTools.BUCKET_VOLUME, 1600000, "Allows you to set how much milibucket of fluid each iron tank blo
This doesn't really need to be millibuckets, that will just confuse people. Buckets are fine grained enough.

2019-01-14 07:26 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/tanks/StandardTank.java
> +            capacity = nbt.getInteger("Capacity");
Do we really want to serialize this? Doesn't this get in the way of balance changes on our end?

2019-01-14 07:26 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
The client should always already know this.

2019-01-14 07:29 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
this is set when the multiblock pattern change notification is received. seems it is no longer received on the client?

2019-01-14 07:30 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
well there are three "pattern changed" event functions... onPatternChanged is called on the client...

StructureLogic fixes this mess.

2019-01-14 07:35 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
Wait no.... onPatternChanged is gated by a isHost check....

2019-01-14 07:36 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
I scrapped this entire chunk of code and started over for StructureLogic because it was so convoluted and inconsistent.

2019-01-14 07:37 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
The Tanks and the Boilers are the only ones that use onPatternLock, just call it from the readData function.

2019-01-14 07:38 UTC, liach commented on src/main/java/mods/railcraft/common/fluids/TankManager.java
> +            data.writeInt(tank.getCapacity());
You can finish your code first and then I can rework on this. I can work on other issues, e.g. jei stuff

2019-01-18 05:36 UTC, liach commented
@covertjaguar I have dropped #1567 related change so that we can derive a better fix for that. The other bugs are clear and can be fixed as it is.

2019-01-18 05:42 UTC, CovertJaguar approved these changes

2019-01-18 05:44 UTC, merged