Fixes #1664
Railcraft/Railcraft pull request #1665
Opened 2019-01-19 14:37 UTC by liach

**The Issue**
 - #1664 
 - #1506
 - Inventory composite crashes on iron golems
 
**The Proposal**
 - Change the throw to an empty iterator since some entities don't have inventories
 - Cleans up some forestry related code
 - Syncs reversal status on gui return to help fix #1506 
 - Change track kit meta handling to take oredict wildcard as a special case for forestry backpacks
 
**Possible Side Effects**
 - The oredict wildcard special case might affect other usages which I am not sure.
 - Dunno why you decided to throw originally for the inventory composite.
 
**Alternatives**
 - I could have returned true meta, but I did not because I don't know if that hurts other usages of track kit

2019-01-19 15:04 UTC, CovertJaguar requested changes

2019-01-19 15:04 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/util/inventory/IInventoryComposite.java
> +                .orElseGet(Collections::emptyIterator);
You have misidentified the problem. InventoryComposite, the standard implementation of this interface, needs to override these new functions.

I'll fix it, so revert this.

2019-01-19 18:15 UTC, liach commented
i will definitely revert that as you initially designed this system, which i do not yet understand throughoutly.

2019-01-20 02:02 UTC, liach commented
Reverted that change.

2019-01-20 09:04 UTC, CovertJaguar approved these changes

2019-01-20 09:04 UTC, merged