Rework post connections
Railcraft/Railcraft pull request #1790
Opened 2019-03-20 12:17 UTC by liach

**The Issue**
Improve post connections, metal cube beacon base, gated track connections, try add post washing
 
**The Proposal**
This is a try to clean up post connections so that we don't need to mingle with it later.
 
**Possible Side Effects**
Changed signal connections to single thick.
Some other visual changes and connection changes as well.
Will work on adding concrete walls later.
 
**Alternatives**
Still a wip, posting for cj to review.

2019-03-22 04:42 UTC, CovertJaguar commented
> Changed signal connections to single thick.

Why?

2019-03-22 05:18 UTC, CovertJaguar requested changes
Nope:
![2019-03-21_22 08 54](https://user-images.githubusercontent.com/1521970/54801987-9c85e680-4c26-11e9-8202-0d6c713efd9d.png)

Um....
![2019-03-21_22 12 12](https://user-images.githubusercontent.com/1521970/54801998-a576b800-4c26-11e9-8524-00d96aef0fd3.png)
![2019-03-21_22 13 12](https://user-images.githubusercontent.com/1521970/54802010-ac9dc600-4c26-11e9-94db-d683427e46d1.png)
![2019-03-21_22 16 04](https://user-images.githubusercontent.com/1521970/54802079-1027f380-4c27-11e9-844d-f7f5ca9728a7.png)

Can you tell the difference between these two pictures?
Before:
![2019-03-19_14 14 48](https://user-images.githubusercontent.com/1521970/54802100-246bf080-4c27-11e9-902f-fe805238d37b.png)
After:
![2019-03-21_22 15 47](https://user-images.githubusercontent.com/1521970/54802111-2a61d180-4c27-11e9-9fc4-6b9f64ff0285.png)

2019-03-22 05:18 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/metals/EnumMetal.java
> +    BLOCK_COPPER(ModuleResources.class, "copper", new MetalCube(), 3f, 10f),
Is there any reason not to just strip out the SimpleCube def? Its a hold over from BlockGeneric.

2019-03-22 05:18 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/BlockPostBase.java
> +        return Column.FULL;
Doesn't this result in crossbeams having a pillar?

2019-03-22 05:18 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/PostConnectionHelper.java
> +    public static ConnectStyle connectMetalPost(IBlockAccess world, BlockPos pos, IBlockState state, EnumFacing side) {
Why rename it? It affects all posts.

2019-03-22 05:18 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/wayobjects/signals/BlockMachineSignal.java
> +        return face != front ? ConnectStyle.SINGLE_THICK : ConnectStyle.NONE;
Pretty sure SINGLE_THINK will look horrible suspended above the tracks.

2019-03-23 15:27 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/PostConnectionHelper.java
> +    public static ConnectStyle connectMetalPost(IBlockAccess world, BlockPos pos, IBlockState state, EnumFacing side) {
Don't think we use this for concrete posts.

2019-03-23 15:28 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/wayobjects/signals/BlockMachineSignal.java
> +        return face != front ? ConnectStyle.SINGLE_THICK : ConnectStyle.NONE;
Hmm, when was single thick used for initially?

2019-03-23 15:28 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/BlockPostBase.java
> +        return Column.FULL;
Hmm, that if above should handle it. This is to fix the no model thing when the post is in air

2019-03-23 15:29 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/aesthetics/metals/EnumMetal.java
> +    BLOCK_COPPER(ModuleResources.class, "copper", new MetalCube(), 3f, 10f),
Thought it was able to hold and share logic. Will change

2019-03-23 20:44 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/PostConnectionHelper.java
> +    public static ConnectStyle connectMetalPost(IBlockAccess world, BlockPos pos, IBlockState state, EnumFacing side) {
We did.

2019-03-23 20:44 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/wayobjects/signals/BlockMachineSignal.java
> +        return face != front ? ConnectStyle.SINGLE_THICK : ConnectStyle.NONE;
Mounting signs and lanterns on posts.

2019-03-23 20:45 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/aesthetics/post/BlockPostBase.java
> +        return Column.FULL;
It definitely adds vertical beams to suspended posts, see my screen shots.

2022-06-20 04:34 UTC, closed without merging