Various fixes
Railcraft/Railcraft pull request #900
Opened 2016-09-23 03:31 UTC by liach

Moved to a RailcraftBlockProperties class
Add BlockMachineAlpha (Not tested)
Improved ITileRotate

2016-09-23 03:33 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/RailcraftBlockProperties.java
> + * ***************************************************************************
Oh I didn't realize the header.

2016-09-23 03:34 UTC, liach commented on src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneRefined.java
> +        if (world.isRemote) {
This is intended to fix that reported crash,

2016-09-23 03:34 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +            masterOven.facing = facing;
Dunno how to set the facing of each block...

2016-09-23 15:10 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +            masterOven.facing = facing;
I suspect they just ask the master

2016-09-23 15:18 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +        WorldPlugin.setBlockState(worldObj, getPos(), getBlockState().withProperty(BlockMachineAlpha.FRONT, facing));
This is certainly wrong, the meta can't support more than 16 states

2016-09-23 15:21 UTC, CovertJaguar requested changes

2016-09-23 21:33 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +        WorldPlugin.setBlockState(worldObj, getPos(), getBlockState().withProperty(BlockMachineAlpha.FRONT, facing));
But it does nothing with the meta. It just update the facing of the tile being called.

2016-09-23 21:34 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +        WorldPlugin.setBlockState(worldObj, getPos(), getBlockState().withProperty(BlockMachineAlpha.FRONT, facing));
For now I will remove this setting of block states.

2016-09-23 21:44 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/alpha/TileSteamOven.java
> +        WorldPlugin.setBlockState(worldObj, getPos(), getBlockState().withProperty(BlockMachineAlpha.FRONT, facing));
Fixed in next commit.

2016-09-23 21:49 UTC, liach commented
Wait, do not merge yet, I got some issue with manipulator textures.

2016-10-02 06:36 UTC, liach commented
I've fixed for those comments but somehow these fixed places does not show as outdated diffs.

2016-10-04 04:15 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneRefined.java
> +        if (world.isRemote) {
In the future, put stuff like this in a separate PR.

2016-10-07 02:31 UTC, liach commented
@CovertJaguar Anything else to fix?

2016-10-07 03:34 UTC, CovertJaguar approved these changes

2016-10-07 03:35 UTC, CovertJaguar commented
Nothing particularly outstanding, but I'm going to sit on this until I start working on this stuff.

2016-11-01 15:57 UTC, closed without merging

2016-11-01 23:25 UTC, Joshwoo70 commented
keep it open so that CJ will remember tp fix it later.

2016-11-02 02:03 UTC, liach commented
Well those fixes are really minor. They are not that important.

2016-11-02 19:26 UTC, CovertJaguar commented
Most important thing is this commit is the Firestone fix...which I know I'm going to forget.