Fixed for block griefing
Railcraft/Railcraft pull request #906
Opened 2016-09-29 05:17 UTC by liach

2016-10-01 16:50 UTC, liach commented
Reference #280

2016-10-02 06:43 UTC, CovertJaguar requested changes

2016-10-02 06:43 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/PlayerPlugin.java
> +            return CartTools.RAILCRAFT_PROFILE;
No...just no...

2016-10-02 06:43 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/gamma/TileDispenserCart.java
> +                            Entity item = cartStack.getItem().createEntity(worldObj, new EntityItem(worldObj, x, y, z, cartStack), cartStack);
I really need to track this function down...

2016-10-02 06:43 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/carts/EntityCartUndercutter.java
> +            }
Can we move this into WorldPlugin? Maybe as a new function, not sure.

2016-10-02 06:43 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/PlayerPlugin.java
> +        return "[Railcraft]";
This probably breaks stuff...I remember some "[Unknown]".equals(string) somewhere.

2016-10-02 06:43 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/PlayerPlugin.java
> +        return "[Railcraft]";
This probably breaks stuff...I remember some "[Unknown]".equals(string) somewhere.

2016-10-04 04:16 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/blocks/machine/gamma/TileDispenserCart.java
> +                            Entity item = cartStack.getItem().createEntity(worldObj, new EntityItem(worldObj, x, y, z, cartStack), cartStack);
Yes, this is wrong, see #905

2016-10-04 06:32 UTC, liach commented
Well I will try to push some change tomorrow.

2016-10-04 06:59 UTC, CovertJaguar requested changes

2016-10-04 06:59 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/PlayerPlugin.java
> -    public static final GameProfile RAILCRAFT_USER_PROFILE = new GameProfile(UUID.nameUUIDFromBytes("[Railcraft]".getBytes()), "[Railcraft]");
This stays.

2016-10-04 07:03 UTC, CovertJaguar commented on src/main/java/mods/railcraft/common/plugins/forge/PlayerPlugin.java
> +        return "[Railcraft]";
Also... "[Railcraft]" should generally have similar to admin permissions, whereas "[Unknown]" would be fully restricted. So returning "[Railcraft]" as a fallback is not generally safe.

2016-10-05 21:50 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/gamma/TileDispenserCart.java
> +                            Entity item = cartStack.getItem().createEntity(worldObj, new EntityItem(worldObj, x, y, z, cartStack), cartStack);
So will you try to merge this pull when I fixed this patch?

2016-10-06 14:13 UTC, liach commented on src/main/java/mods/railcraft/common/blocks/machine/gamma/TileDispenserCart.java
> +                            Entity item = cartStack.getItem().createEntity(worldObj, new EntityItem(worldObj, x, y, z, cartStack), cartStack);
Fixed

2016-10-10 23:22 UTC, liach commented
Should I open a pull which I pick these fixes to 1.10 branch?

2016-10-12 22:57 UTC, CovertJaguar commented
@liach yeah, something like that

2017-02-23 03:17 UTC, liach commented
Should close this one

2017-02-23 03:17 UTC, closed without merging